from django.db import models
from django.contrib.auth.models import User
from cavanish.models import Rooms
from django.core.validators import FileExtensionValidator

# Create your models here.
class Tenant(models.Model):
    user =  models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE, null=True, blank=True)
    legal_first_name = models.TextField(max_length= 99, blank=True)
    legal_last_name = models.TextField(max_length= 99, blank=True)
    AGE = {
       'AGE 18': 18, 'AGE 19': 19, 'AGE 20': 20, 'AGE 21': 21, 'AGE 22': 22, 'AGE 23': 23, 'AGE 24': 24, 'AGE 25': 25, 'AGE 26': 26, 'AGE 27': 27, 'AGE 28': 28, 'AGE 29': 29, 'AGE 30': 30, 'AGE 31': 31, 'AGE 32': 32, 'AGE 33': 33, 'AGE 34': 34, 'AGE 35': 35, 'AGE 36': 36, 'AGE 37': 37, 'AGE 38': 38, 'AGE 39': 39, 'AGE 40': 40, 'AGE 41': 41, 'AGE 42': 42, 'AGE 43': 43, 'AGE 44': 44, 'AGE 45': 45, 'AGE 46': 46, 'AGE 47': 47, 'AGE 48': 48, 'AGE 49': 49, 'AGE 50': 50, 'AGE 51': 51, 'AGE 52': 52, 'AGE 53': 53, 'AGE 54': 54, 'AGE 55': 55, 'AGE 56': 56, 'AGE 57': 57, 'AGE 58': 58, 'AGE 59': 59, 'AGE 60': 60, 'AGE 61': 61, 'AGE 62': 62, 'AGE 63': 63, 'AGE 64': 64, 'AGE 65': 65, 'AGE 66': 66, 'AGE 67': 67, 'AGE 68': 68, 'AGE 69': 69, 'AGE 70': 70, 'AGE 71': 71, 'AGE 72': 72, 'AGE 73': 73, 'AGE 74': 74, 'AGE 75': 75, 'AGE 76': 76, 'AGE 77': 77, 'AGE 78': 78, 'AGE 79': 79, 'AGE 80': 80, 'AGE 81': 81, 'AGE 82': 82, 'AGE 83': 83, 'AGE 84': 84, 'AGE 85': 85, 'AGE 86': 86, 'AGE 87': 87, 'AGE 88': 88, 'AGE 89': 89, 'AGE 90': 90, 'AGE 91': 91, 'AGE 92': 92, 'AGE 93': 93, 'AGE 94': 94, 'AGE 95': 95, 'AGE 96': 96, 'AGE 97': 97, 'AGE 98': 98, 'AGE 99': 99
    }
    age = models.TextField(max_length = 20, choices=AGE , blank=True)
    NATIONALITY = {
        "AF":"Afghanistan",
        "AX":"Aland Islands",
        "AL":"Albania",
        "DZ":"Algeria",
        "AS":"American Samoa",
        "AD":"Andorra",
        "AO":"Angola",
        "AI":"Anguilla",
        "AQ":"Antarctica",
        "AG":"Antigua and Barbuda",
        "AR":"Argentina",
        "AM":"Armenia",
        "AW":"Aruba",
        "AU":"Australia",
        "AT":"Austria",
        "AZ":"Azerbaijan",
        "BS":"Bahamas",
        "BH":"Bahrain",
        "BD":"Bangladesh",
        "BB":"Barbados",
        "BY":"Belarus",
        "BE":"Belgium",
        "BZ":"Belize",
        "BJ":"Benin",
        "BM":"Bermuda",
        "BT":"Bhutan",
        "BO":"Bolivia, Plurinational State of",
        "BQ":"Bonaire, Sint Eustatius and Saba",
        "BA":"Bosnia and Herzegovina",
        "BW":"Botswana",
        "BV":"Bouvet Island",
        "BR":"Brazil",
        "IO":"British Indian Ocean Territory",
        "BN":"Brunei Darussalam",
        "BG":"Bulgaria",
        "BF":"Burkina Faso",
        "BI":"Burundi",
        "KH":"Cambodia",
        "CM":"Cameroon",
        "CA":"Canada",
        "CV":"Cape Verde",
        "KY":"Cayman Islands",
        "CF":"Central African Republic",
        "TD":"Chad",
        "CL":"Chile",
        "CN":"China",
        "CX":"Christmas Island",
        "CC":"Cocos (Keeling) Islands",
        "CO":"Colombia",
        "KM":"Comoros",
        "CG":"Congo",
        "CD":"Congo, The Democratic Republic of the",
        "CK":"Cook Islands",
        "CR":"Costa Rica",
        "CI":"Côte d'Ivoire",
        "HR":"Croatia",
        "CU":"Cuba",
        "CW":"Curaçao",
        "CY":"Cyprus",
        "CZ":"Czech Republic",
        "DK":"Denmark",
        "DJ":"Djibouti",
        "DM":"Dominica",
        "DO":"Dominican Republic",
        "EC":"Ecuador",
        "EG":"Egypt",
        "SV":"El Salvador",
        "GQ":"Equatorial Guinea",
        "ER":"Eritrea",
        "EE":"Estonia",
        "ET":"Ethiopia",
        "FK":"Falkland Islands (Malvinas)",
        "FO":"Faroe Islands",
        "FJ":"Fiji",
        "FI":"Finland",
        "FR":"France",
        "GF":"French Guiana",
        "PF":"French Polynesia",
        "TF":"French Southern Territories",
        "GA":"Gabon",
        "GM":"Gambia",
        "GE":"Georgia",
        "DE":"Germany",
        "GH":"Ghana",
        "GI":"Gibraltar",
        "GR":"Greece",
        "GL":"Greenland",
        "GD":"Grenada",
        "GP":"Guadeloupe",
        "GU":"Guam",
        "GT":"Guatemala",
        "GG":"Guernsey",
        "GN":"Guinea",
        "GW":"Guinea-Bissau",
        "GY":"Guyana",
        "HT":"Haiti",
        "HM":"Heard Island and McDonald Islands",
        "VA":"Holy See (Vatican City State)",
        "HN":"Honduras",
        "HK":"Hong Kong",
        "HU":"Hungary",
        "IS":"Iceland",
        "IN":"India",
        "ID":"Indonesia",
        "IR":"Iran, Islamic Republic of",
        "IQ":"Iraq",
        "IE":"Ireland",
        "IM":"Isle of Man",
        "IL":"Israel",
        "IT":"Italy",
        "JM":"Jamaica",
        "JP":"Japan",
        "JE":"Jersey",
        "JO":"Jordan",
        "KZ":"Kazakhstan",
        "KE":"Kenya",
        "KI":"Kiribati",
        "KP":"Korea, Democratic People's Republic of",
        "KR":"Korea, Republic of",
        "KW":"Kuwait",
        "KG":"Kyrgyzstan",
        "LA":"Lao People's Democratic Republic",
        "LV":"Latvia",
        "LB":"Lebanon",
        "LS":"Lesotho",
        "LR":"Liberia",
        "LY":"Libya",
        "LI":"Liechtenstein",
        "LT":"Lithuania",
        "LU":"Luxembourg",
        "MO":"Macao",
        "MK":"Macedonia, Republic of",
        "MG":"Madagascar",
        "MW":"Malawi",
        "MY":"Malaysia",
        "MV":"Maldives",
        "ML":"Mali",
        "MT":"Malta",
        "MH":"Marshall Islands",
        "MQ":"Martinique",
        "MR":"Mauritania",
        "MU":"Mauritius",
        "YT":"Mayotte",
        "MX":"Mexico",
        "FM":"Micronesia, Federated States of",
        "MD":"Moldova, Republic of",
        "MC":"Monaco",
        "MN":"Mongolia",
        "ME":"Montenegro",
        "MS":"Montserrat",
        "MA":"Morocco",
        "MZ":"Mozambique",
        "MM":"Myanmar",
        "NA":"Namibia",
        "NR":"Nauru",
        "NP":"Nepal",
        "NL":"Netherlands",
        "NC":"New Caledonia",
        "NZ":"New Zealand",
        "NI":"Nicaragua",
        "NE":"Niger",
        "NG":"Nigeria",
        "NU":"Niue",
        "NF":"Norfolk Island",
        "MP":"Northern Mariana Islands",
        "NO":"Norway",
        "OM":"Oman",
        "PK":"Pakistan",
        "PW":"Palau",
        "PS":"Palestinian Territory, Occupied",
        "PA":"Panama",
        "PG":"Papua New Guinea",
        "PY":"Paraguay",
        "PE":"Peru",
        "PH":"Philippines",
        "PN":"Pitcairn",
        "PL":"Poland",
        "PT":"Portugal",
        "PR":"Puerto Rico",
        "QA":"Qatar",
        "RE":"Réunion",
        "RO":"Romania",
        "RU":"Russian Federation",
        "RW":"Rwanda",
        "BL":"Saint Barthélemy",
        "SH":"Saint Helena, Ascension and Tristan da Cunha",
        "KN":"Saint Kitts and Nevis",
        "LC":"Saint Lucia",
        "MF":"Saint Martin (French part)",
        "PM":"Saint Pierre and Miquelon",
        "VC":"Saint Vincent and the Grenadines",
        "WS":"Samoa",
        "SM":"San Marino",
        "ST":"Sao Tome and Principe",
        "SA":"Saudi Arabia",
        "SN":"Senegal",
        "RS":"Serbia",
        "SC":"Seychelles",
        "SL":"Sierra Leone",
        "SG":"Singapore",
        "SX":"Sint Maarten (Dutch part)",
        "SK":"Slovakia",
        "SI":"Slovenia",
        "SB":"Solomon Islands",
        "SO":"Somalia",
        "ZA":"South Africa",
        "GS":"South Georgia and the South Sandwich Islands",
        "ES":"Spain",
        "LK":"Sri Lanka",
        "SD":"Sudan",
        "SR":"Suriname",
        "SS":"South Sudan",
        "SJ":"Svalbard and Jan Mayen",
        "SZ":"Swaziland",
        "SE":"Sweden",
        "CH":"Switzerland",
        "SY":"Syrian Arab Republic",
        "TW":"Taiwan, Province of China",
        "TJ":"Tajikistan",
        "TZ":"Tanzania, United Republic of",
        "TH":"Thailand",
        "TL":"Timor-Leste",
        "TG":"Togo",
        "TK":"Tokelau",
        "TO":"Tonga",
        "TT":"Trinidad and Tobago",
        "TN":"Tunisia",
        "TR":"Turkey",
        "TM":"Turkmenistan",
        "TC":"Turks and Caicos Islands",
        "TV":"Tuvalu",
        "UG":"Uganda",
        "UA":"Ukraine",
        "AE":"United Arab Emirates",
        "GB":"United Kingdom",
        "US":"United States",
        "UM":"United States Minor Outlying Islands",
        "UY":"Uruguay",
        "UZ":"Uzbekistan",
        "VU":"Vanuatu",
        "VE":"Venezuela, Bolivarian Republic of",
        "VN":"Viet Nam",
        "VG":"Virgin Islands, British",
        "VI":"Virgin Islands, U.S.",
        "WF":"Wallis and Futuna",
        "YE":"Yemen",
        "ZM":"Zambia",
        "ZW":"Zimbabwe"
}
    nationality = models.TextField(max_length = 20, choices=NATIONALITY, blank=True)
    info = models.CharField(max_length=20, help_text='Enter field documentation', blank=True)
    GENDER = {
        "M": "Male",
        "F": "Female"
    }
    gender =  models.CharField(max_length=20, choices=GENDER, blank=True)
    passport = models.FileField(upload_to="Passport", blank=True, validators=[FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])
    brp = models.FileField(upload_to="BRP", blank=True, validators=[FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])
    weekly_pay = models.BooleanField(default=True)
    monthly_pay = models.BooleanField(default=False)
    date_joined = models.TimeField(auto_now_add=True)

   #Metadata
    class Meta :
       ordering = ['user']


    def __str__(self):
       return f"{self.legal_first_name} {self.legal_last_name} Details"