# Generated by Django 5.0.1 on 2024-01-16 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Room Name', max_length=50)),
                ('room_number', models.SlugField()),
                ('rent_amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(max_length=99)),
                ('content', models.CharField(max_length=9999)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('name', models.TextField(default='Payment')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount_payed', models.PositiveIntegerField()),
                ('rent_date_start', models.DateField()),
                ('rent_date_end', models.DateField()),
                ('date_payed', models.DateTimeField()),
                ('payment_remark', models.TextField(default='Thanks For Using Cavanish Home', max_length=999)),
                ('room', models.ManyToManyField(related_name='payments', to='cavanish.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=9999)),
                ('description', models.CharField(max_length=99999)),
                ('rooms_total', models.IntegerField()),
                ('annoucements', models.CharField(max_length=9999)),
                ('house_image1', models.ImageField(blank=True, height_field=700, upload_to='uploads', width_field=700)),
                ('house_image2', models.ImageField(blank=True, height_field=700, upload_to='uploads', width_field=700)),
                ('house_image3', models.ImageField(blank=True, height_field=700, upload_to='uploads', width_field=700)),
                ('house_image4', models.ImageField(blank=True, height_field=700, upload_to='uploads', width_field=700)),
                ('house_image5', models.ImageField(blank=True, height_field=700, upload_to='uploads', width_field=700)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cavanish.rooms')),
            ],
        ),
    ]
