# Generated by Django 5.0.1 on 2024-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavanish', '0003_payments_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='rooms',
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Through our Application'), ('Cash', 'Cash Deposit')], max_length=99),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rent_amount',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.ManyToManyField(to='cavanish.rooms'),
        ),
    ]
